### ISSUE TITLE
Burn Wallet for Binance

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#100]
**Problem definition**
A new burn wallet is required for no-seniorage, and is needed to be implemented for March 1st (dependent on governance)

**Feature specification**
- [x] Create new burn wallet for Binance
- [x] Test burn wallet feature

**Additional context**
.

**Acceptance criteria**
- [x] New burn wallet is live in mainnet

**Comment by StrathCole** [comment]
Why would that be necessary?

**Comment by edk208** [comment]
Binance has asked yesterday we implement this as well.  They want to make sure that what they burn, stays burned, even if seigniorage is re-enabled.

**Comment by edk208** [comment]
Hi @nghuyenthevinh2000 here is the seigniorage code, https://github.com/classic-terra/core/blob/dba9f22d3d6a0fdc2aa0b8bc48e6ed2256a8ddb0/x/treasury/keeper/seigniorage.go#L28 where the total amount burned per epoch is reminted...  
Here is where the total amount is recorded.
https://github.com/classic-terra/core/blob/dba9f22d3d6a0fdc2aa0b8bc48e6ed2256a8ddb0/x/treasury/keeper/seigniorage.go#L13
if we create a separate burn wallet, that can be excluded from this amount, it should not participate in the seignorage calculation.

**Comment by StrathCole** [comment]
> Binance has asked yesterday we implement this as well. They want to make sure that what they burn, stays burned, even if seigniorage is re-enabled.

So another thing that has to go through governance before 1.0.6 …

**Comment by fragwuerdig** [comment]
I hope this is NOT with 1st march deadline? Because that would be quite unfair tbh... to state this in a manner of: "Ah, and by the way, we want that burn wallet too..."

**Comment by StrathCole** [comment]
> I hope this is NOT with 1st march deadline? Because that would be quite unfair tbh... to state this in a manner of: "Ah, and by the way, we want that burn wallet too...". Now, as we are half way through...
> 
> The idea itself is great. However, it SHOULD be implemented as module account to which EVERYONE can send to burn without seignorage mints and exempt tax. NOT Binance-only.

Yes agreed. This should not be anything that needs to be forced prior March 1st. If I remember correctly they were fine with the current seigniorage to zero for now. Of course this could be re-instated by governance, but Binance can simply stop the burn then.

**Comment by StrathCole** [comment]
Honest question: Does the narrow time frame that Binance provided in terms of implementing all requests (including having them pass governance) impose any kind of risk in terms of doing things faster than they would normally be done?

**Comment by edk208** [comment]
I will suggest that this go into the next release (not 1.0.6).
