### ISSUE TITLE
Validator Min. Commission 5%

### ISSUE THREAD

**Issue by fragwuerdig** [classic-terra/core#109]
**Problem definition**
With the passing of proposal 11322 the community expressed the wish to implement a minimum commission of 5% for validators on the network. This highly relates to #89.

Update:  Given that this is feature in Cosmos SDK 0.46, a temporary solution that allows for a minimum 5% commission to be enforced for all validators should be sufficient.

**Comment by inon-man** [comment]
This issue reminds me of the millions of people who suffer from the side effects of policies created without deep reflection by the government. It sounds simple, but it requires a lot of research.

CosmosSDK does not allow us to query participated in voting for closed proposals which is frustrating. I wish to see how many addresses actually participated in voting and how the voting power is distributed.

Terra Classic's token economics are completely broken, so I don't think it's mandatory to implement just because a proposal is passed.

**Comment by inon-man** [comment]
There could be a misunderstanding in what I wrote above, but my opinion is that in-depth discussions is required, rather than rushing to create and apply solution because the proposal is passed.

**Comment by ZaradarBH** [comment]
I agree with @inon-man and have always been of the opinion that in the current situation the "Tokenomics of Terra" are broken to the point where we have to assume that governance is owned by the few lucky  people who caught the bottom and that we will have to build for a long time to attract enough new investors to dilute that voting power in a meaningful way. This consequently is also why trying to "force redelegation via constraints" is never going to work until we can associate addresses with a DID component ala https://hypersign.id/ or https://identity.foundation/ion/.

With that said I think the min  commission makes sense for another reason, namely ensuring the validators are actually economically viable to run. As such that is more important to me then trying to enforce decentralization via centralized code changes, and arguments about voting power (which is already tightly controlled). The best way to achieve this imho is by incentivize the network and governance to course correct via introducing new features that can incentives "real world utility" that can be taxed and increase the rewards for the network validators to the point where they can more then break even and thus do not have to resort to "veto blocking to collect fees" or "partitioning their validators to circumvent the BFT guard".

**Comment by ZaradarBH** [comment]
See discussion @ **https://github.com/classic-terra/core/discussions/127**

**Comment by LuncBurner** [comment]
Re-opened this item as we should have resourcing to have this completed during Q2, and due to it passing governance.  It will be prioritized such that it does not impact the proposed timing of the upgrade to parity.

**Comment by nghuyenthevinh2000** [comment]
https://github.com/cosmos/cosmos-sdk/pull/10529

waiting for core to update to cosmos - sdk 46, then gov change params for min commission

**Comment by alchemist-ti** [comment]
# Set validator min conmission rate

## Abstract

This poposal aims to set the minimum commission rate(aka. `min_commission_rate`) for validators to 5%, and it's beeter to change the minimum commission rate via `ParamsChangeProposal`.

Implementation

### Option 1

Add `ante` module that stores the `min_commission_rate` parameter and checks the commission rate of validator in `anteHandler` before delivering `stakingtypes.MsgCreateValidator` and `stakingtypes.MsgEditValidator`.

Reference: https://github.com/terra-money/core/pull/47

### Option 2

If we don't need to change `min_commission_rate` via `ParamsChangeProposal`, we can just hardcode the `min_commission_rate=5%` in `anteHandler`. Nso need to add `ante` module.

### Option 3

Fork `cosmos-sdk` and cherry-pick this PR: https://github.com/cosmos/cosmos-sdk/pull/10529. We already use a forked `cosmos-sdk` in our repo, so it does not violate our design principles.

### Option1 vs Option2 vs Option3

| Option | Code | Upgrade cosmos-sdk to v0.46 | User experience after cosmos-sdk to v0.46 |
| --- | --- | --- | --- |
| Option1 | More | Need to migrate params and remove `ante` module | ParamsChangeProposal.subspace `ante` to `staking` |
| Option2 | Less | Need to migrate params | smooth |
| Option3 | Less | No need: proto diff refer https://github.com/classic-terra/cosmos-sdk/compare/v0.45.13-classic...cosmos:cosmos-sdk:v0.46.0 | smooth |
 
### Migration

Each option requires a forced increase of the validator's commission to 5%.

We can implement it in the next `UpgradeHandler`, which contains the following logic:

* if `val.commission` < `min_commission_rate`, update `val.commission` to `min_commission_rate`.

**Comment by StrathCole** [comment]
What is with validators that have set MAX commission rate to < 5% ?

**Comment by fragwuerdig** [comment]
> I am good with option 3

Me too.

**Comment by alchemist-ti** [comment]
> What is with validators that have set MAX commission rate to < 5% ?

will be update to 5%

**Comment by fragwuerdig** [comment]
@alchemist-ti - following @StrathCole's suggestion I would add this logic to upgrade handler

```
If min_commission > val.max_commission
val.max_comission=min_commission
```

**Comment by alchemist-ti** [comment]
> @alchemist-ti - following @StrathCole's suggestion I would add this logic to upgrade handler
> 
> ```
> If min_commission > val.max_commission
> val.max_comission=min_commission
> ```

Yeah, make sense. ❤️  I updated to `upgrade handler` logic.

**Comment by LuncBurner** [comment]
Proceeded with option #3 as per Alchemist-ti's recommendation.  Attempting to include this in the v2.1.0 release -- to be confirmed.
