### ISSUE TITLE
Provision AWS Access and Permissions

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#110]
**Problem definition**
An instance of AWS has been configured at the administration level for the L1 team.  However, non-administrative permissions need to be configured for the development team, with billing configured for the various virtual machines to be set up.  

**Feature specification**
- [x] Integrate AWS IAM Identity Center with Office 365 Azure AD tenant **(Tobias)**
- [x] Setup IAM Roles & Users with appropriate permissions **(Tobias)**

**Additional context**
.

**Acceptance criteria**
- [x] Confirm that IAM works for other team members

**Comment by ZaradarBH** [comment]
@LuncBurner I need you to send me the admin accounts for our AWS subscription as well as the admin account for the Office 365 setup so I can wire our Active Directory into AWS IAM.

**Comment by ZaradarBH** [comment]
@edk208 @inon-man @fragwuerdig @nghuyenthevinh2000 I have scheduled an appointment with one of my m8s from the UK who is a certified AWS ninja. If you have any resources you need configured let me know and I will sort it out with Pete in our XP session on Wednesday.

**Comment by nghuyenthevinh2000** [comment]
what is m8s?

**Comment by ZaradarBH** [comment]
> what is m8s?

m8s is just internerd slang for "mates" (friends) :)

**Comment by ZaradarBH** [comment]
AWS Control Tower: https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html
AWS Route53: https://aws.amazon.com/route53/
AWS CloudFront: https://aws.amazon.com/cloudfront/
AWS IAM Identity Center: https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html
AWS WAF: https://aws.amazon.com/waf/
AWS Azure AD: https://docs.aws.amazon.com/singlesignon/latest/userguide/azure-ad-idp.html

**Comment by ZaradarBH** [comment]
How to test:

1) Navigate to https://d-9d670761e1.awsapps.com/start
2) Login using your 0375 account
3) Select the "AWS Account" app tile
4) Expand the "L1 Task Force" account accordion
5) Select "management console" for GUI or "Command line or programmatic access" for CLI/SDK access
