### ISSUE TITLE
signature verification failed; please verify account number and chain-id: unauthorized 

### ISSUE THREAD

**Issue by TheArchitect123** [classic-terra/core#114]
I'm trying to broadcast a transaction via the api 
**/cosmos/tx/v1beta1/txs.**

I'm serialising the entire transaction as a **protobuf**, and the **simulation api works fine**. 
If I broadcast a transaction via **/cosmos/tx/v1beta1/txs/simulate**, I get the following response:
```

{
  "gas_info": {
    "gas_wanted": "50000000",
    "gas_used": "56369"
  },
  "result": {
    "data": "Ch4KHC9jb3Ntb3MuYmFuay52MWJldGExLk1zZ1NlbmQ=",
    "log": "[{\"events\":[{\"type\":\"coin_received\",\"attributes\":[{\"key\":\"receiver\",\"value\":\"terra17lmam6zguazs5q5u6z5mmx76uj63gldnse2pdp\"},{\"key\":\"amount\",\"value\":\"100uluna\"}]},{\"type\":\"coin_spent\",\"attributes\":[{\"key\":\"spender\",\"value\":\"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v\"},{\"key\":\"amount\",\"value\":\"100uluna\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/cosmos.bank.v1beta1.MsgSend\"},{\"key\":\"sender\",\"value\":\"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v\"},{\"key\":\"module\",\"value\":\"bank\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"terra17lmam6zguazs5q5u6z5mmx76uj63gldnse2pdp\"},{\"key\":\"sender\",\"value\":\"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v\"},{\"key\":\"amount\",\"value\":\"100uluna\"}]}]}]",
    "events": [
      {
        "type": "message",
        "attributes": [
          {
            "key": "YWN0aW9u",
            "value": "L2Nvc21vcy5iYW5rLnYxYmV0YTEuTXNnU2VuZA==",
            "index": false
          }
        ]
      },
      {
        "type": "coin_spent",
        "attributes": [
          {
            "key": "c3BlbmRlcg==",
            "value": "dGVycmExeDQ2cnFheTRkM2Nzc3E4Z3h4dnF6OHh0Nm53bHo0dGQyMGszOHY=",
            "index": false
          },
          {
            "key": "YW1vdW50",
            "value": "MTAwdWx1bmE=",
            "index": false
          }
        ]
      },
      {
        "type": "coin_received",
        "attributes": [
          {
            "key": "cmVjZWl2ZXI=",
            "value": "dGVycmExN2xtYW02emd1YXpzNXE1dTZ6NW1teDc2dWo2M2dsZG5zZTJwZHA=",
            "index": false
          },
          {
            "key": "YW1vdW50",
            "value": "MTAwdWx1bmE=",
            "index": false
          }
        ]
      },
      {
        "type": "transfer",
        "attributes": [
          {
            "key": "cmVjaXBpZW50",
            "value": "dGVycmExN2xtYW02emd1YXpzNXE1dTZ6NW1teDc2dWo2M2dsZG5zZTJwZHA=",
            "index": false
          },
          {
            "key": "c2VuZGVy",
            "value": "dGVycmExeDQ2cnFheTRkM2Nzc3E4Z3h4dnF6OHh0Nm53bHo0dGQyMGszOHY=",
            "index": false
          },
          {
            "key": "YW1vdW50",
            "value": "MTAwdWx1bmE=",
            "index": false
          }
        ]
      },
      {
        "type": "message",
        "attributes": [
          {
            "key": "c2VuZGVy",
            "value": "dGVycmExeDQ2cnFheTRkM2Nzc3E4Z3h4dnF6OHh0Nm53bHo0dGQyMGszOHY=",
            "index": false
          }
        ]
      },
      {
        "type": "message",
        "attributes": [
          {
            "key": "bW9kdWxl",
            "value": "YmFuaw==",
            "index": false
          }
        ]
      }
    ]
  }
}
```

However if I try to upload the transaction via "**/cosmos/tx/v1beta1/txs.**" I get the following response.
"**signature verification failed; please verify account number and chain-id: unauthorized**"

**Here's a Json of the model that I pass the Cosmos Rest Backend.**
```
{
   "body":{
      "messages":[
         {
            "typeUrl":"/cosmos.bank.v1beta1.MsgSend",
            "value":"Cix0ZXJyYTF4NDZycWF5NGQzY3NzcThneHh2cXo4eHQ2bndsejR0ZDIwazM4dhIsdGVycmExN2xtYW02emd1YXpzNXE1dTZ6NW1teDc2dWo2M2dsZG5zZTJwZHAaDAoFdWx1bmESAzEwMA=="
         }
      ],
      "memo":"",
      "timeoutHeight":0,
      "extensionOptions":[
         
      ],
      "nonCriticalExtensionOptions":[
         
      ]
   },
   "authInfo":{
      "signerInfos":[
         {
            "publicKey":{
               "typeUrl":"/cosmos.crypto.secp256k1.PubKey",
               "value":"CiECOzOoUkNEBhsSNky6IP4KGrNtRIar9FG7fOvRHqIkHls="
            },
            "modeInfo":{
               "single":{
                  "mode":"SignModeDirect"
               }
            },
            "sequence":278
         }
      ],
      "fee":{
         "amounts":[
            {
               "denom":"uluna",
               "amount":"1756317"
            }
         ],
         "gasLimit":62005,
         "payer":"",
         "granter":"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"
      }
   },
   "signatures":[
      "CmBNRVVDSVFDeHFIQ3ZjbkJJcmVrb01BRVlMMWg4dkVuYUJ1Qyt6bWZmalVYVmJFRXFEZ0lnRHRYM3NvaThQbS9RTjU2cmtVcDBTM2R4U21RUVR1eXBEcUJMWXYwejRncz0SRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiECOzOoUkNEBhsSNky6IP4KGrNtRIar9FG7fOvRHqIkHlsZAAAAAADgY0AhAAAAAABgcUA="
   ]
}
```

**Then I upload the entire transaction as the following JSON object:**
```
{
   "mode":"BROADCAST_MODE_BLOCK",
   "tx_bytes":"Co0BCooBChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEmoKLHRlcnJhMXg0NnJxYXk0ZDNjc3NxOGd4eHZxejh4dDZud2x6NHRkMjBrMzh2Eix0ZXJyYTE3bG1hbTZ6Z3VhenM1cTV1Nno1bW14NzZ1ajYzZ2xkbnNlMnBkcBoMCgV1bHVuYRIDMTAwEpkBClEKRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiECOzOoUkNEBhsSNky6IP4KGrNtRIar9FG7fOvRHqIkHlsSBAoCCAEYlgISRAoQCgV1bHVuYRIHMTc1NjMxNxC15AMiLHRlcnJhMXg0NnJxYXk0ZDNjc3NxOGd4eHZxejh4dDZud2x6NHRkMjBrMzh2GvwBQ21CTlJWVkRTVkZFVVc1RmMwRlhXREpPYkRVM1dYZ3paRWRrT1ZwWGFuSjBiMUJIYzNaclFsSk9ZVWw0TnpkUFJGZENRVWxuVjBWM2JTOU9lR1UxZFdwVE9EWjJVMll5TVdKemVWZ3pRbXRHYUc5bGRscGxSRVZUZDI5V2FEbGpPRDBTUmdvZkwyTnZjMjF2Y3k1amNubHdkRzh1YzJWamNESTFObXN4TGxCMVlrdGxlUklqQ2lFQ096T29Va05FQmhzU05reTZJUDRLR3JOdFJJYXI5Rkc3Zk92UkhxSWtIbHNaQUFBQUFBRGdZMEFoQUFBQUFBQmdjVUE9",
   "sequences":[
      "278"
   ],
   "fee_granter":"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"
}

```
## Version
v0.45.1

## Steps to Reproduce
Simply protobuf serialise the transaction Tx Object, and pass it into the Json (final entry) above, and run a post on the api:
**/cosmos/tx/v1beta1/txs.**

Then you will get the message:
"signature verification failed; please verify account number and chain-id: unauthorized"

So I'm not sure what I'm doing wrong here.
I'm using ECDSA Signing to generate the signature with the private key, and running verification is successful. 
The public/private keys look correct, and everything matches the data that cosmos looks like it requires for a successful broadcast.

So I'm not sure what's going on?

**Comment by ZaradarBH** [comment]
Assigned to @LuncBurner until its been put in scope. :)

**Comment by LuncBurner** [comment]
**Problem Description**
"signature verification failed; please verify account number and chain-id: unauthorized"

**Additional Context**
- [ ] Review issue and determine root cause of potential bug

**Acceptance Criteria**
- [ ] Issue has been resolved
- [ ] Communicate with end user

**Comment by inon-man** [comment]
It is normal for the simulation to succeed as it skips signature validation.

How did you generate the signed transaction? There must be something wrong with generating the signature. Please check account_number, sequence, chain_id, and appropriate private key.

**Comment by nghuyenthevinh2000** [comment]
> "signature verification failed; please verify account number and chain-id: unauthorized"

Most of the time, 
* if it is account number, you wait a bit and then send again.
* if it is chain-id, you are typing a wrong chain-id.
* Or maybe, you provide wrong sequence 278

I just query signer terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v here:

```
{
  "account": {
    "@type": "/cosmos.auth.v1beta1.BaseAccount",
    "address": "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v",
    "pub_key": {
      "@type": "/cosmos.crypto.secp256k1.PubKey",
      "key": "AjszqFJDRAYbEjZMuiD+ChqzbUSGq/RRu3zr0R6iJB5b"
    },
    "account_number": "2432842",
    "sequence": "232"
  }
}
```

sequence 278 seems wrong

**Comment by TheArchitect123** [comment]
How did you query the signer? Do you mean you decoded the signature? Or did you decode from the bech32 address?

**Comment by nghuyenthevinh2000** [comment]
https://lcd.terra.dev/cosmos/auth/v1beta1/accounts/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v

**Comment by TheArchitect123** [comment]
> > "signature verification failed; please verify account number and chain-id: unauthorized"
> 
> Most of the time, 
> * if it is account number, you wait a bit and then send again.
> * if it is chain-id, you are typing a wrong chain-id.
> * Or maybe, you provide wrong sequence 278
> 
> I just query signer terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v here (I am assuming that signer is the same as sender, spender)
> 
> ```
> {
>   "account": {
>     "@type": "/cosmos.auth.v1beta1.BaseAccount",
>     "address": "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v",
>     "pub_key": {
>       "@type": "/cosmos.crypto.secp256k1.PubKey",
>       "key": "AjszqFJDRAYbEjZMuiD+ChqzbUSGq/RRu3zr0R6iJB5b"
>     },
>     "account_number": "2432842",
>     "sequence": "232"
>   }
> }
> ```
> 
> sequence 278 seems wrong

What tool did you use to decode the signer by the way?

**Comment by nghuyenthevinh2000** [comment]
most of the time, signer will be sender

**Comment by TheArchitect123** [comment]
But I'm testing this against Pisco.
https://pisco-lcd.terra.dev/cosmos/auth/v1beta1/accounts/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v

And the account number matches up

**Comment by TheArchitect123** [comment]
> But I'm testing this against Pisco. https://pisco-lcd.terra.dev/cosmos/auth/v1beta1/accounts/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v
> 
> And the account number matches up

But I'm testing this against Pisco.
https://pisco-lcd.terra.dev/cosmos/auth/v1beta1/accounts/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v

And the account number matches up

**Comment by TheArchitect123** [comment]
also is https://lcd.terra.dev/ the classic testnet url or mainnet?
I believe columbus is mainnet

**Comment by TheArchitect123** [comment]
I still get the same issue against https://lcd.terra.dev/cosmos/auth/v1beta1/accounts/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v

**Comment by nghuyenthevinh2000** [comment]
Oh, I thought you were on mainnet. I will check again on Picasso

**Comment by ZaradarBH** [comment]
Your testing two different networks, hence the results.

https://lcd.terra.dev/cosmos/auth/v1beta1/accounts/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v (v1 mainnet)
https://pisco-lcd.terra.dev/cosmos/auth/v1beta1/accounts/terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v (v2 testnet)

Rebel-1 is deprecated and afaik so is Rebel-2. The current classic  testnet should  be Rogue-1. You  can find testnet assets here @ https://github.com/terra-rebels/classic-testnet.

Overall we need to clean-up the test networks and consolidate the assets in our new GH org. But probably not something we will be able to do until Q2.

I hope this additional context helps resolve this issue. :)

**Comment by TheArchitect123** [comment]
Thanks @ZaradarBH. But there's no documentation anywhere for Rogue-1.
I can't find the url for classic testnet.

@edk208 can you please post or send me a link to any documentation for rogue-1 (chain-id). Where are the active url endpoints? Thanks for your help

**Comment by ZaradarBH** [comment]
I just looked on our internal slack, I think maybe Rogue-1 might actually have been deprecated and the current testnet is actually Rebel-2. The endpoint info is as follows:

TESTNET - chain-id = rebel-2
faucet - https://faucet.terrac.dev/
finder - https://finder.terrac.dev/classictestnet/
station - https://station.terrac.dev/
lcd - https://lcd.terrac.dev/
fcd - https://fcd.terrac.dev/

We will add this info into the documentation that is scheduled for this sprint so most likely the situation will be "mostly remedied" by the end of this sprint (2 weeks from now).

If this info helps you resolve your  issue please close it and forward input to documentation to this issue  https://github.com/classic-terra/core/issues/81

**Comment by TheArchitect123** [comment]
Urls all work @ZaradarBH.
I'm closing this issue now. Thanks
