### ISSUE TITLE
Classic TestNet (Rebel-1) Accounts Api is failing

### ISSUE THREAD

**Issue by TheArchitect123** [classic-terra/core#116]
The classic Api (https://rebel1.grouptwo.org/swagger/#/) is failing to return a correct account (404) for a Bech32 address that I pass it. It works perfectly on mainnet (classic).

I've provided more details on a twitter post. 
https://twitter.com/realArchitectDG/status/1620738483945107456

**Comment by ZaradarBH** [comment]
Assigned to @LuncBurner  until its been put in scope. :)

**Comment by LuncBurner** [comment]
**Problem Definition**
The classic Api (https://rebel1.grouptwo.org/swagger/#/) is failing to return a correct account (404) for a Bech32 address

**Additional Context**
- [ ] Investigate issue, determine root cause of potential bug
- [ ] Communicate findings to end user

**Acceptance Criteria**
- [ ] Issue has been resolved

**Comment by ZaradarBH** [comment]
@TheArchitect123 have you tried targeting Rogue-1 instead? Rebel-1 is most likely out-of-sync because it was deprecated months ago. @edk208 should  be able to provide you with updates on what test networks are usable :)

**Comment by ZaradarBH** [comment]
@TheArchitect123 try targeting Rebel-2 with the endpoints I provided in issue #114 :)

**Comment by edk208** [comment]
@TheArchitect123  rebel-2 is stable with v1.1.0.  Please let me know if the issue still exists.  

TESTNET - chain-id = rebel-2
faucet - https://faucet.terrac.dev/
finder - https://finder.terrac.dev/classictestnet/
station - https://station.terrac.dev/
lcd - https://lcd.terrac.dev/
fcd - https://fcd.terrac.dev/

**Comment by TheArchitect123** [comment]
Urls all work. Thanks
