### ISSUE TITLE
[BUG] Node stops syncing with "ERR CONSENSUS FAILURE!!!"

### ISSUE THREAD

**Issue by Szymongib** [classic-terra/core#122]
**Describe the bug**
After upgrading to `v1.0.5` (and later to `v1.0.5-full-archive`) we started to observe that RPC node stops syncing few times a day.

In the logs we can  see:
```
terra_classic_1  | 5:59PM ERR CONSENSUS FAILURE!!! err="unable to delete version 11532000 with 1 active readers" module=consensus stack="goroutine 13667 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:726 +0x4c\npanic({0x1a68f20, 0xc0fb0132a8})\n\truntime/panic.go:884 +0x212\ngithub.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc000eee000)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.5/store/rootmulti/store.go:431 +0x1b6\ngithub.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000eee000)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.5/store/rootmulti/store.go:405 +0x186\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc001459520)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:305 +0x1e9\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc0005639e0)\n\tgithub.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:264 +0xb6\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x50?)\n\tgithub.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:93 +0x22\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc003170820, 0x7}}, {0xc003170830, 0xa}, 0x1, 0xaff74e, {{0xc0f1c136c0, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.14/state/execution.go:228 +0x269\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc003170820, 0x7}}, {0xc003170830, 0xa}, 0x1, 0xaff74e, {{0xc0f1c136c0, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.14/state/execution.go:180 +0x6ee\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0000e6700, 0xaff74e)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1635 +0xa1d\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0000e6700, 0xaff74e)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1546 +0x313\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1481 +0x94\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc0000e6700, 0xaff74e, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1519 +0xbf7\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0000e6700, 0xc0f188b360, {0xc005bd20f0, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:2132 +0x18dc\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0000e6700, 0xc0f188b360, {0xc005bd20f0?, 0xc0efdf7200?})\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1930 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0000e6700, {{0x23d1000?, 0xc0efdd37c0?}, {0xc005bd20f0?, 0x0?}})\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:838 +0x170\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0000e6700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:762 +0x3f9\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:378 +0x11c\n"
```

Restarting the node fixes the problem but it returns few hours later.

**To Reproduce**
I do not know how to reliably reproduce.

**Context & versions**
`v1.0.5` and `v1.0.5-full-archive`

**Comment by nghuyenthevinh2000** [comment]
thanks for your ticket, I will look into it

**Comment by nghuyenthevinh2000** [comment]
https://github.com/cosmos/iavl/blob/v0.17.3/nodedb.go#L291

**Comment by nghuyenthevinh2000** [comment]
you are doing snap shot right?

**Comment by nghuyenthevinh2000** [comment]
code in cosmos - sdk related to iavl exporter: https://github.com/classic-terra/cosmos-sdk/blob/release/v0.44.x/store/rootmulti/store.go#L709-L752

**Comment by Szymongib** [comment]
FYI we were running node with some custom pruning settings. Changing pruning to `default` seems to solve the issue.

**Comment by nghuyenthevinh2000** [comment]
It appears that while the node is creating a snapshot for height 11532000 in here: https://github.com/classic-terra/cosmos-sdk/blob/release/v0.44.x/baseapp/abci.go#L336. So there is still a writter attached to that version 11532000.

The writer for version 11532000 is not Close() yet: https://github.com/classic-terra/cosmos-sdk/blob/release/v0.44.x/store/rootmulti/store.go#L715

The node then decides to prune 11532000 in new height 11535000 (for example), PruneInterval is less than 300 blocks. The system decides to remove 11532000 which leads to the above panic.

What is your in "terrad start"? If exists

1. --pruning-interval
2. --pruning
3. --pruning-keep-every
4. --pruning-keep-recent

**Comment by qezz** [comment]
@nghuyenthevinh2000 Before reverting it back to `default`, it was a following:

```toml
# app.toml
pruning = "custom"
pruning-keep-recent = "100"
pruning-keep-every = "0"
pruning-interval = "10"
```

**Comment by nghuyenthevinh2000** [comment]
@qezz what is the current block that you have the upper error?

**Comment by qezz** [comment]
I don't think I've seen the error since yesterday.

From the monitoring, it has happened at height `11531110`, and in the logs it was `unable to delete version 11532000` (as @Szymongib mentioned above). Also, for another node it happened at the same height, pruning `... 11531000`

So
11531110 : 11532000
11531110 : 11531000

Yeah, it seems like a configuration problem, but it wasn't happening before the upgrade to `v1.0.5` 🤷‍♂️

**Comment by qezz** [comment]
Thank you for the clarifications!

**Comment by nghuyenthevinh2000** [comment]
Interesting, I will compare between v1.0.4 and v1.0.5

**Comment by qezz** [comment]
I'm wrong about `11531110 : 11532000`, it happened later,

11532110 : 11532000

**Comment by nghuyenthevinh2000** [comment]
You can try to increase interval higher until it is reliable. If you are satisfied with the explanation and solution, please close this issue.

I will have to create another ticket to see why this kind of problem only surfaces after v1.0.5

**Comment by Szymongib** [comment]
Thanks

**Comment by nghuyenthevinh2000** [comment]
there is an upgrade block height check in every new block which may lead to more read operation.
