### ISSUE TITLE
Add v1.1.0 features to @terra-money NPM

### ISSUE THREAD

**Issue by inon-man** [classic-terra/core#140]
## Problem
Station does not support tax exemption feature

## Background
1. Station seems that it will continue to use terra-money/terra.js ; too many dependencies
2. terra.js uses both legacy.proto (terra.proto@^0.1.7) for Classic and terra.proto (terra.proto@^2) for Terra 2.0 at the same time
3. terra.proto generates typescript files from ../terrad/proto which is a git submodule of `terra-money/core`, using protocol-gen-go. However, current classic/core no longer generates cosmos-sdk, tendermint proto files

## Actions
- [x] Obtain npm publish permission for @classic-terra
- [x] Add Tax exemption feature to @classic-terra/terra.proto
   - pin *.proto files as static instead of using git submodule
- [x] Fix legacy.proto dependencies from terra.js source code
- [x] Modify terra.js/package.json; Make legacy.proto to use @classic-terra/terra.proto
- [x] Create a PR to terra-money/terra.js
- [x] Create a PR to terra-money/station

**Comment by ZaradarBH** [comment]
@Man12C can you help us with the publishing? We should be able to re-use the existing NPM Publish workflow @ https://github.com/classic-terra/terra.js/actions/workflows/npm-publish.yml if we add a NPM_TOKEN from the TCV org to our org secrets. Alternatively you can provide me with a valid secret and I can do it :)

**Comment by ZaradarBH** [comment]
New PR @ https://github.com/terra-money/terra.js/pull/348

**Comment by ZaradarBH** [comment]
I have created a PR for Station here @ https://github.com/terra-money/station/pull/326 that targets the new NPM package version. v3.1.8

**Comment by ZaradarBH** [comment]
https://www.npmjs.com/package/@terra-money/terra.js/v/3.1.8
