### ISSUE TITLE
Establish IBC to Kujira

### ISSUE THREAD

**Issue by fragwuerdig** [classic-terra/core#153]
I was asked by several community members around @lunaticlunclover to establish IBC to Kujira. This would ultimately enable Terra Classic to be listed on FIN exchange or being used as stablecoin collateral.

- [x] Scope of work?
- [x] Archive node for Kujira
- [x] Establish new connection?
- [x] speak to Kujira about LUNC listing

**Comment by LuncBurner** [comment]
LCD nodes for relayer communications synced and running.  Target for Kujira IBC launch is mid-June.

**Comment by LuncBurner** [comment]
@fragwuerdig Till has advised this task is ~85% completed.

**Comment by LuncBurner** [comment]
New connection and IBC transfer to and from Kujira completed.
