### ISSUE TITLE
Look at issues with liveness tests

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/core#171]
**Context**
@fragwuerdig looked into the liveness test issue .

The local testnet nodes don't come up, because the gentxs cannot be delivered on InitChainer (non-ok exit code but panic message is redacted - so no idea what's going on). The root cause is TBD.

The liveness test script is tricked into believing all testnet containers started properly, because the nodes need 2-3s seconds before they die. So the docker ps command shows them as being started and the script continues. But then the nodes die.

@fragwuerdig first thought there is an issue with a PR https://github.com/classic-terra/core/pull/121. But when switching to main (where https://github.com/classic-terra/core/pull/121 is present as well), then the testnet nodes come up properly...

One can test/evaluate/reproduce this locally by doing:

make clean localnet-start && ./contrib/localnet/localnet_liveness.sh

This is starting liveness test immediately after docker-compose up -d.

And if you do make localnet-start then you see the nodes being started in background. Then they die in background. After that do docker-compose up without -d flag and you will be able to see the error messages while the nodes die.

PS: There is an issue with https://github.com/classic-terra/core/pull/121: if TESTNET_NVAL < 6 then some nodes do not get a genesis.json. So they die ungracefully. I will take care of this in another PR.

**Task**
- [ ] Identify root cause of "unexpected exit code" issue in liveness tests

**Comment by fragwuerdig** [comment]
Regarding your PS: Yes, that's right. Also noticed this. But unfortunately it's not the issue with that "message redacted" thingy 😭
