### ISSUE TITLE
[BUG] 501 for Simulation Api (Was working Yesterday)

### ISSUE THREAD

**Issue by TheArchitect123** [classic-terra/core#175]
**Describe the bug**
Something has changed under Classic Mainnet. This was working yesterday, and none of my client code has changed.

![image](https://user-images.githubusercontent.com/20945125/224848555-40a744c7-87cd-498d-8914-93dca31a8511.png)

Also Swagger is not working too. If you run this url here (it returns this):
![image](https://user-images.githubusercontent.com/20945125/224848863-762961d8-ef0a-4d44-b54e-d97905da7ed5.png)

**Comment by TheArchitect123** [comment]
This is a really big problem @edk208

**Comment by edk208** [comment]
I believe station has moved from TFL LCDs to Allnodes.   You can use this https://terra-classic.publicnode.com/
It is possible that it is being shutdown?

**Comment by TheArchitect123** [comment]
Ok it works.
However has classic testnet url changed? 
Or is it still being hosted by L1 Task Force?
Thanks @edk208
