### ISSUE TITLE
Impact analysis on upgrading Cosmwasm v0.16.6 => v1.1.1

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/core#18]
**Problem definition**
Impact analysis of upgrade to Cosmwasm v1.1.1 to assess effect on migrating L2 wasm contracts from 0.16.6.

**Acceptance criteria**
Complete governance process and determine if community is ready for the upgrade

**Additional context**
- [x] Set up feedback form with questionnaires in MS forms
- [x] LuncBurnArmy to contact existing utilities and smart contract holders.
- [x] Reach out to various DAO's (metagloria)
- [x] Conduct analysis, develop document outlining pros/cons of implementing upgrade and impacts
- [x] Review analysis and decide on whether or not to proceed.

**Comment by ZaradarBH** [comment]
Input from Ed: 
- Augment the current WASM virtual machine to fit with Cosmwasm v1.0.0. 
- Reach out to Assaf from Secret Network to understand dual VM setup.

**Comment by ZaradarBH** [comment]
Input from Ed: We need to research how to augment the current WASM virtual machine to fit with Cosmwasm v1.0.0. Reach out to Assaf from Secret Network to understand dual VM setup.

**Comment by ZaradarBH** [comment]
I am assuming by "current WASM virtual machine" he means "wasmd" which is documented in detail @ https://github.com/CosmWasm/wasmd

**Comment by ZaradarBH** [comment]
StrathCole has indicated that he would be happy to help with this analysis :)

**Comment by LuncBurner** [comment]
Have reached out to Strath Cole via email with respect to this item.

**Comment by fragwuerdig** [comment]
I already started to set up a questionnaire on paper. I will discuss it with my wife before presenting the questions. @ZaradarBH can you please set up/research a tool that would enable us to create actual questionnaires?

**Comment by LuncBurner** [comment]
@fragwuerdig That's fantastic.  Once you have the questions ready, we'll put it into a survey format that we can easily release to the community (i.e. Survey Monkey or Microsoft Forms, etc.).

**Comment by ZaradarBH** [comment]
Nah, I think you can safely kick me off this issue  :)

**Comment by LuncBurner** [comment]
Contacted all utilities on-chain via email and/or contact method listed on website (i.e. Twitter).  Created a dashboard view of results that display findings from survey.

**Comment by StrathCole** [comment]
> Contacted all utilities on-chain via email and/or contact method listed on website (i.e. Twitter). Created a dashboard view of results that display findings from survey.

Is that dashboard public?

**Comment by fragwuerdig** [comment]
This issue can be closed?
