### ISSUE TITLE
[BUG] Station extension bug

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [classic-terra/core#195]
**Describe the bug**

When I go into terra station for localterra, this is what I got:

<img width="1512" alt="Screenshot 2023-03-28 at 20 42 59" src="https://user-images.githubusercontent.com/23058164/228257551-52c06d4b-522d-4c56-a93a-30c7510949c9.png">

**To Reproduce**

I start a v2.0.0-apha localnet, I register "localhost:1317" to terra station extension LocalNet. The error above shows up.

1. clone: https://github.com/classic-terra/core.git
2. go into branch: testnet-refactor
3. make localnet-start
4. cat build/node0/terrad/key_seed.json |  jq '.secret'
5. restore a key in terra station extension
6. it should output the error above

**Context & versions**
1. I think the main problem lies in api mismatch somehow.
2. i am using canonical terra station so it should be on this repo: https://github.com/terra-money/station-extension

**Comment by LuncBurner** [comment]
@nghuyenthevinh2000 I think this issue can be closed?  I believe that this is an older item.  I will close it, if it still applies, please let me know.
