### ISSUE TITLE
Test v2.0.0 Upgrade on Rebel-2 Testnet

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#201]
**Problem definition**
Test v2.0.0 upgrade on Rebel-2 Testnet as a 'dress rehearsal' upgrade

**Acceptance criteria**

- [x] Make upgrade guideline document
- [x] Prepare the rebel-2 Testnet accordingly
- [x] Join rebel-2 testnet with full node archive
- [x] Prepare genesis.json and serve on s3
- [x] Prepare addrbook.json and serve on s3
- [x] optionally create snapshot and serve on s3 (if feasable)
- [x] Announce to join the testnet to TerraClassic validator discord group
- [x] Help validators to onboard
- [x] Perform the actual upgrade

**Comment by nghuyenthevinh2000** [comment]
@fragwuerdig can you aid Steve in writing a document and guide annoucing to validators for testnet upgrade on bajor-1?

**Comment by fragwuerdig** [comment]
@nghuyenthevinh2000  we have to clarify what the voting period on rebel-2 is. From what I can see after joining the rebel-2 network it is unreasonably high (like 4 millenia). We have to wait whether we would be able to reset the network. Need feedback from @edk208. Also @edk208: Can you clarify whether you are running the network on a vanilla v1.1.0 binary or whether you modified fork heights/validator max. voting power to set up the net easily?

**Comment by edk208** [comment]
voting period is only like 5-10 minutes i think.  I can double check.  Rebel-2 was upgraded from v1.0.5.  It still contains height/validator max guards from before.

**Comment by LuncBurner** [comment]
We have put out a request for validators to join the Rebel-2 testnet, and will be looking to schedule a date for a 'dress rehearsal upgrade' in the testnet prior to scheduling on columbus-5.

**Comment by LuncBurner** [comment]
New testnet required, due to governance not functioning correctly on Rebel-2.

**Comment by fragwuerdig** [comment]
Been working on preparing the testnet. Governance is working on `rebel-2`. I extended the voting and deposit period from a few minutes to three days. I also lowered the quorum to 20%. Been busy setting up a second validator (alongside with oracle feeder). I also announced the testnet in der Validators Discord Group. Let's hope they join :/

**Comment by LuncBurner** [comment]
Rebel-2 testnet upgrade has been scheduled for Thursday May 4th at approximately 11am EST.

**Comment by StrathCole** [comment]
> 

Will there be a V1 testnet afterwards to still be able to test contracts before deployment to classic net?

**Comment by LuncBurner** [comment]
> > 
> 
> Will there be a V1 testnet afterwards to still be able to test contracts before deployment to classic net?

We are aiming to have the upgrade to v2.0.0 completed for mainnet on May 17th.  Are you able to test locally between May 4th and May 17th?

**Comment by StrathCole** [comment]
When you upgrade classic, have you made sure the necessary rust bindings are all there? Have not checked how to query oracle on v2 (because that is something mainnet doesn't have).

I can't test locally, i have no local testnet. So I have to postpone all NFT collection releases to after classic main update.

**Comment by nghuyenthevinh2000** [comment]
You can still upload 0.16, it is still the same

**Comment by StrathCole** [comment]
> You can still upload 0.16, it is still the same

Okay, sorry. then I mixed the v2 with the cosmwasm update in my head.

**Comment by StrathCole** [comment]
I am currently experiencing very high broadcast times for contract executions on testnet. Not sure if that's something that is known to happen at the moment.
![Bildschirmfoto von 2023-05-06 15-57-25](https://user-images.githubusercontent.com/7449529/236628757-a36fe821-a480-411b-8cd8-3fbf5ec7101c.png)

Previous tx took ~10 minutes plus.

**Comment by arunadaybasu** [comment]
Are you guys like doing something on the terrarebels mainnet? I was trying to use it for an app but changed it to the publicnode now. Can we have some updates regarding this?

**Comment by LuncBurner** [comment]
@arunadaybasu We do not have anything to do with the endpoints.  I believe that TR had posted they were doing an upgrade and that they were switching over to the publicnode until their upgrade is completed.  They would be best positioned to advise you on this item.  Hope you are having a great weekend!

**Comment by nghuyenthevinh2000** [comment]
> I am currently experiencing very high broadcast times for contract executions on testnet. Not sure if that's something that is known to happen at the moment. ![Bildschirmfoto von 2023-05-06 15-57-25](https://user-images.githubusercontent.com/7449529/236628757-a36fe821-a480-411b-8cd8-3fbf5ec7101c.png)
> 
> Previous tx took ~10 minutes plus.

can you send me the tx, smart contract address? 

this is on rebels - 2 right?

**Comment by nghuyenthevinh2000** [comment]
I think we are good to close this
