### ISSUE TITLE
Oracle Feeder

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#213]
**Describe the bug**
It has been discovered that there is a price issue between the old oracle feeder and the Sha256 feeder.  This was discovered through long-duration testing on mainnet.  

**(if applicable) suggested solution**
- [ ] Ensure full backwards compatibility with previous version of Oracle feeder.

**Comment by nghuyenthevinh2000** [comment]
This is newest oracle feeder result of mindfulness validator

<img width="1364" alt="Screenshot 2023-04-30 at 16 43 51" src="https://user-images.githubusercontent.com/23058164/235346558-a1b14297-0f00-4d1b-badd-340433d10f3f.png">

Exchange rate range is compatible with Allnodes and Orion 

<img width="1363" alt="Screenshot 2023-04-30 at 16 43 59" src="https://user-images.githubusercontent.com/23058164/235346590-b48cfe4f-3fd4-4eab-ab95-b8a3930cf086.png">
<img width="1360" alt="Screenshot 2023-04-30 at 16 44 05" src="https://user-images.githubusercontent.com/23058164/235346600-48c3a646-4ad9-42df-a927-c33d525b0bf1.png">

No misses so far after 9005

https://terra-classic-lcd.publicnode.com/terra/oracle/v1beta1/validators/terravaloper1t2gmacpsvgykwgw3az6qnqw82cm8dl5yy78cc5/miss

Running on mainnet in docker for further 1 week to confirm stability

Pushed to @fragwuerdig for testnet testing
