### ISSUE TITLE
Create Cosmwasm Upgrade Documentation

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#214]
**Problem definition**
Create migration documentation for Smart Contract owners to upgrade to Cosmwasm v1.1.0.

Use as a starting guide and customize:  
https://docs.terra.money/develop/guides/smart-contracts/upgrade-cosmwasm/

**Acceptance criteria**

- [x] Create migration documentation for Cosmwasm v1.1.0
- [x] Offer smart contract owners post-upgrade support

**Comment by shackra** [comment]
as always, the best path forward with this is trying to set up a validator and see what works does and what doesn't

**Comment by LuncBurner** [comment]
https://github.com/classic-terra/terra-bindings/blob/main/MIGRATIONS.md
