### ISSUE TITLE
Station Testing

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#217]
**Problem definition**
Updated proto for classic v2, has been created.  Needs to be published to to npm registry and implemented into station.
https://github.com/classic-terra/terra.proto/pull/3

**Acceptance criteria**
Published to NPM registry.  Station governance testing completed.

- [ ] Creating a gov proposal for min initial deposit on station frontend following proto update.
- [ ] Confirm update successful

**Comment by ZaradarBH** [comment]
Keep in mind that the terra.proto lib has to live "side-by-side" in terra.js, so you have to bump that as well in order to get the new proto lib into Station and you will need to take any divergence by TFL in their version of terra.js into account while doing so 🙏
