### ISSUE TITLE
Anti - corruption layer for new CosmWasm

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [classic-terra/core#222]
New version of CosmWasm introduces some changes to custom query and custom msg structure. 

To ensure compatibility between old and new structure, an anti corruption layer is needed through Terra bindings smart contract.

Add an anti - corruption layer to Terra bindings smart contract so that it can handle old custom msg structure. Old and new terra bindings client library is compatible with some migrations

1. https://github.com/classic-terra/terra-bindings
2. https://crates.io/crates/classic-bindings

**Comment by arunadaybasu** [comment]
Can you explain a little bit about what this is technically? What does "anti corruption" entail to? What layer are you adding?

**Comment by nghuyenthevinh2000** [comment]
> Can you explain a little bit about what this is technically? What does "anti corruption" entail to? What layer are you adding?

That is to avoid sudden data corruption when old smart contract one has not migrated to new struct yet

**Comment by arunadaybasu** [comment]
Thanks a lot.

**Comment by nghuyenthevinh2000** [comment]
Testing old reflect smart contract on new wasm

**Comment by nghuyenthevinh2000** [comment]
confirmed with @StrathCole
