### ISSUE TITLE
Can't start the Node after upgrate

### ISSUE THREAD

**Issue by zhangpeizheng123** [classic-terra/core#224]
Hello,I upgraded the Terra Node to the latest version(V2.0.1),when I started the node,I got this error " unable to resolve type URL /cosmos.vesting.v1beta1.PeriodicVestingAccount",any help?

**Comment by nghuyenthevinh2000** [comment]
can you give me more context, what is the interaction that leads to the above error

**Comment by nghuyenthevinh2000** [comment]
maybe you will want to:

```
git fetch --tags --force
git checkout tags/v2.0.1
```

**Comment by zhangpeizheng123** [comment]
I used this "git checkout tags/v2.0.1" to build the node,and I still got the same error.

**Comment by zhangpeizheng123** [comment]
> can you give me more context, what is the interaction that leads to the above error

When I upgraded the Node version to v2.0.1, I got this error "panic: version 12815210 was already saved to different hash BE29BAE0F89E7B52613E89573F053D1A357B057C7BC309B50BC2B50EB92A1B9C (existing hash BF9C00452CB93D160771C78F2500EDEF88E2173FA9193D349A67254F87A4DE05)";
I thought it was the old data didn't  match the new version data, so I changed the “--home” directory to a new one and I started the Node again,then I got another error "unable to resolve type URL /cosmos.vesting.v1beta1.PeriodicVestingAccount"; Pls tell me how to handle this ,thanks!

**Comment by nghuyenthevinh2000** [comment]
try `git fetch --tags --force`

**Comment by zhangpeizheng123** [comment]
> git checkout tags/v2.0.1

Still got this error "panic: version 12815210 was already saved to different hash BE29BAE0F89E7B52613E89573F053D1A357B057C7BC309B50BC2B50EB92A1B9C (existing hash BF9C00452CB93D160771C78F2500EDEF88E2173FA9193D349A67254F87A4DE05)";

**Comment by zhangpeizheng123** [comment]
> try `git fetch --tags --force`

got this error "panic: version 12815210 was already saved to different hash BE29BAE0F89E7B52613E89573F053D1A357B057C7BC309B50BC2B50EB92A1B9C (existing hash BF9C00452CB93D160771C78F2500EDEF88E2173FA9193D349A67254F87A4DE05)";

**Comment by zhangpeizheng123** [comment]
Use this command:    ./terrad rollback  ,and then I restarted the node ,it works!
