### ISSUE TITLE
Missing Lunc Upon Redelegation

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#248]
**Describe the bug**

User Discovered Bug for Re-delegation from one validator to another:
Tx Hash: 8AC26B62A48572A06FD4438D38DF8559342374BD359CCF63044A556851F26C20

"_From Thor to Coinpayu, transferred 5 million, received 4999999.999998.  Then thor remained in the delegations list with 0 lunc.  If you see in finder I have several validators in delegations list which have 0 lunc.  Obviously they do not generate rewards but they remain on the list.  They had the same problem."

**Comment by nghuyenthevinh2000** [comment]
I will check on cli to be certain

**Comment by LuncBurner** [comment]
It appears to only be a fraction of 1 LUNC token, so the amount is small.  If this is a correct behavior, then once we have confirmed we can proceed with closing out the issue.

**Comment by LuncBurner** [comment]
@alchemist-ti Any thought on this item?  Correct Cosmos SDK behavior vs. bug?  @nghuyenthevinh2000 Did you find anything by checking cli?

**Comment by LuncBurner** [comment]
This is a known issue for redelegation.

**Comment by alchemist-ti** [comment]
> @alchemist-ti Any thought on this item? Correct Cosmos SDK behavior vs. bug? @nghuyenthevinh2000 Did you find anything by checking cli?

Yes, as @inon-man said, it's a correct Cosmos SDK behavior.
