### ISSUE TITLE
ANC Token Display in Rebel Finder and Station

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#250]
**Problem definition**
ANC token is not appearing in finder.

**Acceptance criteria**
- [x] Investigate bug and determine root cause
- [x] Update to ensure ANC is being displayed correctly
- [x] Deploy patch

**Comment by nghuyenthevinh2000** [comment]
we should send this to terra - rebels

**Comment by LuncBurner** [comment]
@fragwuerdig Can you review @inon-man's PR?

**Comment by fragwuerdig** [comment]
I forwarded to various dApp providers to try.

**Comment by LuncBurner** [comment]
@inon-man@fragwuerdig Ability to search for ANC token in Finder works correctly?  Can I close this issue?

**Comment by nghuyenthevinh2000** [comment]
https://finder.terrarebels.net/classic/address/terra18vnrzlzm2c4xfsx382pj2xndqtt00rvhu24sqe

it is displaying now
