### ISSUE TITLE
[BUG] Consensus breaking change by feeshare feature

### ISSUE THREAD

**Issue by inon-man** [classic-terra/core#267]
**Describe the bug**
The node will break the consensus (wrong Block.Header.AppHash) after applying changes after https://github.com/classic-terra/core/commit/1e7936c622a6519596d302a8970b6f684ebd282b

**To Reproduce**
Apply https://github.com/classic-terra/core/commit/1e7936c622a6519596d302a8970b6f684ebd282b with an existing network.

**Context & versions**
Since https://github.com/classic-terra/core/commit/1e7936c622a6519596d302a8970b6f684ebd282b applied to main (luckily it didn't get applied until v2.1.1)

**Solution**
v2 upgrade [proposal](https://station.terrarebels.net/proposal/11367) has been done about 4 months ago, so [upgrade handler](https://github.com/classic-terra/core/blob/4207f83223d74c47fc5be7aa680ed4dbbf0c279a/app/upgrades/v2/upgrades.go#L22-L28) would never be called. We need to do a proper migration with new governance proposal or do a rollback.

**Comment by nghuyenthevinh2000** [comment]
feeshare has never been properly tested so I am leaving it out of all release so far. But, we can think about integrating it in the next release

**Comment by nghuyenthevinh2000** [comment]
It is going to be dealt with in next release anyway right after this wasm

**Comment by nghuyenthevinh2000** [comment]
Feeshare is left out from v2.1.x release so no worries about that

![Screenshot_20230618_063442_GitHub.jpg](https://github.com/classic-terra/core/assets/23058164/59d97620-1993-446a-bae6-cb94a4835fd7)
