### ISSUE TITLE
Build New Development Testnet:  Picard-1

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#286]
**Problem definition**
A testnet is required for the enablement and integrated testing of USTC, with the market module enabled.

**Acceptance criteria**
- [ ] Create new testnet, importing genesis state 
- [ ] Enable FCD, LCD, RPC, etc.
- [ ] Ensure full Station connectivity

**Comment by fragwuerdig** [comment]
Make it so.

**Comment by fragwuerdig** [comment]
Closed as outdated.
