### ISSUE TITLE
Cannot deploy contract on classic network

### ISSUE THREAD

**Issue by garudanodes** [classic-terra/core#289]
Issue Description:
Cannot deploy contract on classic network

Step:
I add this classic chain into config.json file.
"classic": {
    "columbus-5": {
      "chainID": "columbus-5",
      "lcd": "https://terra-classic-lcd.publicnode.com/",
      "gasAdjustment": 5,
      "gasPrices": {
        "uluna": 28.325,
        "usdr": 0.52469,
        "uusd": 0.75,
        "ukrw": 850,
        "umnt": 2142.855,
        "ueur": 0.625,
        "ucny": 4.9,
        "ujpy": 81.85,
        "ugbp": 0.55,
        "uinr": 54.4,
        "ucad": 0.95,
        "uchf": 0.7,
        "uaud": 0.95,
        "usgd": 1,
        "uthb": 23.1,
        "usek": 6.25,
        "unok": 6.25,
        "udkk": 4.5,
        "uidr": 10900,
        "uphp": 38,
        "uhkd": 5.85,
        "umyr": 3,
        "utwd": 20
      },
      "prefix": "terra",
      "coinType": "330",
      "baseAsset": "uluna",
      "name": "Terra Classic",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/TerraClassic.svg",
      "isClassic": true,
      "explorer": {
        "address": "https://finder.terra.money/classic/address/%7B%7D",
        "tx": "https://finder.terra.money/classic/tx/%7B%7D",
        "validator": "https://finder.terra.money/classic/validator/%7B%7D",
        "block": "https://finder.terra.money/classic/block/%7B%7D"
      }
    }
  },

and I already data that we need in keys.terrain.js

but when I run this command, I got an error that the classic chain can't be found.

![image](https://github.com/classic-terra/core/assets/120026168/d885b0b7-c71d-4e74-8e72-a4c07602543a)

**Comment by garudanodes** [comment]
> Try to rename config.js to config.terrain.js
> 
> https://github.com/terra-money/terrain/blob/main/README.md#project-structure

done but still got same error

**Comment by garudanodes** [comment]
{
  "global": {
    "base": {
      "instantiation": {
        "instantiateMsg": {
          "name": "BingBong NFT Project",
          "symbol": "BINGBONG",
          "minter": "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v",
          "owner": "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"
        }
      }
    }
  },
  "classic": {
    "axelar-dojo-1": {
      "chainID": "axelar-dojo-1",
      "lcd": "https://lcd-axelar.imperator.co",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uaxl": 0.007
      },
      "prefix": "axelar",
      "coinType": "118",
      "baseAsset": "uaxl",
      "name": "Axelar",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Axelar.svg",
      "ibc": {
        "fromTerra": "channel-19",
        "toTerra": "channel-0"
      },
      "explorer": {
        "address": "https://www.mintscan.io/axelar/account/{}",
        "tx": "https://www.mintscan.io/axelar/txs/{}",
        "validator": "https://www.mintscan.io/axelar/validators/{}",
        "block": "https://www.mintscan.io/axelar/blocks/id/{}"
      }
    },
    "crescent-1": {
      "chainID": "crescent-1",
      "lcd": "https://mainnet.crescent.network:1317",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ucre": 0.01
      },
      "prefix": "cre",
      "coinType": "118",
      "baseAsset": "ucre",
      "name": "Crescent",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Crescent.svg",
      "ibc": {
        "fromTerra": "channel-49",
        "toTerra": "channel-0"
      },
      "explorer": {
        "address": "https://www.mintscan.io/crescent/account/{}",
        "tx": "https://www.mintscan.io/crescent/txs/{}",
        "validator": "https://www.mintscan.io/crescent/validators/{}",
        "block": "https://www.mintscan.io/crescent/blocks/id/{}"
      }
    },
    "juno-1": {
      "chainID": "juno-1",
      "lcd": "https://lcd-juno.mib.tech",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ujuno": 0.0025
      },
      "prefix": "juno",
      "coinType": "118",
      "baseAsset": "ujuno",
      "name": "Juno",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Juno.svg",
      "ibc": {
        "fromTerra": "channel-20",
        "toTerra": "channel-27"
      },
      "explorer": {
        "address": "https://www.mintscan.io/juno/account/{}",
        "tx": "https://www.mintscan.io/juno/txs/{}",
        "validator": "https://www.mintscan.io/juno/validators/{}",
        "block": "https://www.mintscan.io/juno/blocks/id/{}"
      }
    },
    "columbus-5": {
      "chainID": "columbus-5",
      "lcd": "https://terra-classic-lcd.publicnode.com",
      "gasAdjustment": 5,
      "gasPrices": {
        "uluna": 28.325,
        "usdr": 0.52469,
        "uusd": 0.75,
        "ukrw": 850,
        "umnt": 2142.855,
        "ueur": 0.625,
        "ucny": 4.9,
        "ujpy": 81.85,
        "ugbp": 0.55,
        "uinr": 54.4,
        "ucad": 0.95,
        "uchf": 0.7,
        "uaud": 0.95,
        "usgd": 1,
        "uthb": 23.1,
        "usek": 6.25,
        "unok": 6.25,
        "udkk": 4.5,
        "uidr": 10900,
        "uphp": 38,
        "uhkd": 5.85,
        "umyr": 3,
        "utwd": 20
      },
      "prefix": "terra",
      "coinType": "330",
      "baseAsset": "uluna",
      "name": "Terra Classic",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/TerraClassic.svg",
      "isClassic": true,
      "explorer": {
        "address": "https://finder.terra.money/classic/address/{}",
        "tx": "https://finder.terra.money/classic/tx/{}",
        "validator": "https://finder.terra.money/classic/validator/{}",
        "block": "https://finder.terra.money/classic/block/{}"
      }
    }
  },
  "localterra": {
    "localterra": {
      "chainID": "localterra",
      "lcd": "http://localhost:1317",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uluna": 0.15
      },
      "prefix": "terra",
      "coinType": "330",
      "baseAsset": "uluna",
      "name": "LocalTerra",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Terra.svg",
      "explorer": {
        "address": "https://finder.terra.money/localterra/address/{}",
        "tx": "https://finder.terra.money/localterra/tx/{}",
        "validator": "https://finder.terra.money/localterra/validator/{}",
        "block": "https://finder.terra.money/localterra/block/{}"
      }
    }
  },
  "mainnet": {
    "akashnet-2": {
      "chainID": "akashnet-2",
      "lcd": "https://rest.cosmos.directory/akash",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uakt": 0.025
      },
      "prefix": "akash",
      "coinType": "118",
      "baseAsset": "uakt",
      "name": "Akash",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Akash.svg",
      "ibc": {
        "fromTerra": "channel-45",
        "toTerra": "channel-56"
      },
      "explorer": {
        "address": "https://www.mintscan.io/akash/account/{}",
        "tx": "https://www.mintscan.io/akash/txs/{}",
        "validator": "https://www.mintscan.io/akash/validators/{}",
        "block": "https://www.mintscan.io/akash/blocks/id/{}"
      }
    },
    "axelar-dojo-1": {
      "chainID": "axelar-dojo-1",
      "lcd": "https://lcd-axelar.imperator.co",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uaxl": 0.007
      },
      "prefix": "axelar",
      "coinType": "118",
      "baseAsset": "uaxl",
      "name": "Axelar",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Axelar.svg",
      "ibc": {
        "fromTerra": "channel-6",
        "toTerra": "channel-11"
      },
      "explorer": {
        "address": "https://www.mintscan.io/axelar/account/{}",
        "tx": "https://www.mintscan.io/axelar/txs/{}",
        "validator": "https://www.mintscan.io/axelar/validators/{}",
        "block": "https://www.mintscan.io/axelar/blocks/id/{}"
      }
    },
    "carbon-1": {
      "chainID": "carbon-1",
      "lcd": "https://query-api.carbon.network/",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "swth": 1000
      },
      "prefix": "swth",
      "coinType": "118",
      "baseAsset": "swth",
      "name": "Carbon",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Carbon.svg",
      "alliance": true,
      "ibc": {
        "fromTerra": "channel-36",
        "toTerra": "channel-12",
        "icsFromTerra": {
          "contract": "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
          "toTerra": "channel-16",
          "fromTerra": "channel-41"
        }
      },
      "explorer": {
        "address": "https://scan.carbon.network/account/{}?net=main",
        "tx": "https://scan.carbon.network/transaction/{}?net=main",
        "validator": "https://scan.carbon.network/validator/{}?net=main",
        "block": "https://scan.carbon.network/block/{}?net=main"
      }
    },
    "cheqd-mainnet-1": {
      "chainID": "cheqd-mainnet-1",
      "lcd": "https://api.cheqd.net",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ncheq": 50
      },
      "prefix": "cheqd",
      "coinType": "118",
      "baseAsset": "ncheq",
      "name": "cheqd",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Cheqd.svg",
      "ibc": {
        "fromTerra": "channel-89",
        "toTerra": "channel-9"
      },
      "explorer": {
        "address": "https://explorer.cheqd.io/accounts/{}",
        "tx": "https://explorer.cheqd.io/transactions/{}",
        "validator": "https://explorer.cheqd.io/validators/{}",
        "block": "https://explorer.cheqd.io/blocks/{}"
      }
    },
    "chihuahua-1": {
      "chainID": "chihuahua-1",
      "lcd": "https://api.chihuahua.wtf",
      "gasAdjustment": 2,
      "gasPrices": {
        "uhuahua": 1
      },
      "prefix": "chihuahua",
      "coinType": "118",
      "baseAsset": "uhuahua",
      "name": "Chihuahua",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Huahua.png",
      "ibc": {
        "fromTerra": "channel-44",
        "toTerra": "channel-34"
      },
      "explorer": {
        "address": "https://www.mintscan.io/chihuahua/account/{}",
        "tx": "https://www.mintscan.io/chihuahua/txs/{}",
        "validator": "https://www.mintscan.io/chihuahua/validators/{}",
        "block": "https://www.mintscan.io/chihuahua/blocks/id/{}"
      }
    },
    "comdex-1": {
      "chainID": "comdex-1",
      "lcd": "https://rest.comdex.one",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ucmdx": 0.0025
      },
      "prefix": "comdex",
      "coinType": "118",
      "baseAsset": "ucmdx",
      "name": "Comdex",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Comdex.svg",
      "ibc": {
        "fromTerra": "channel-39",
        "toTerra": "channel-51"
      },
      "explorer": {
        "address": "https://www.mintscan.io/comdex/account/{}",
        "tx": "https://www.mintscan.io/comdex/txs/{}",
        "validator": "https://www.mintscan.io/comdex/validators/{}",
        "block": "https://www.mintscan.io/comdex/blocks/id/{}"
      }
    },
    "cosmoshub-4": {
      "chainID": "cosmoshub-4",
      "lcd": "https://cosmoshub-4.terra.dev",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uatom": 0.025
      },
      "prefix": "cosmos",
      "coinType": "118",
      "baseAsset": "uatom",
      "name": "Cosmos",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Cosmos.svg",
      "ibc": {
        "toTerra": "channel-339",
        "fromTerra": "channel-0"
      },
      "explorer": {
        "address": "https://www.mintscan.io/cosmos/account/{}",
        "tx": "https://www.mintscan.io/cosmos/txs/{}",
        "validator": "https://www.mintscan.io/cosmos/validators/{}",
        "block": "https://www.mintscan.io/cosmos/blocks/id/{}"
      }
    },
    "crescent-1": {
      "chainID": "crescent-1",
      "lcd": "https://mainnet.crescent.network:1317",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ucre": 0.01
      },
      "prefix": "cre",
      "coinType": "118",
      "baseAsset": "ucre",
      "name": "Crescent",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Crescent.svg",
      "ibc": {
        "fromTerra": "channel-37",
        "toTerra": "channel-27"
      },
      "explorer": {
        "address": "https://www.mintscan.io/crescent/account/{}",
        "tx": "https://www.mintscan.io/crescent/txs/{}",
        "validator": "https://www.mintscan.io/crescent/validators/{}",
        "block": "https://www.mintscan.io/crescent/blocks/id/{}"
      }
    },
    "mainnet-3": {
      "chainID": "mainnet-3",
      "lcd": "https://rest.mainnet.decentr.xyz",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "udec": 0.025
      },
      "prefix": "decentr",
      "coinType": "118",
      "baseAsset": "udec",
      "name": "Decentr",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Decentr.svg",
      "ibc": {
        "toTerra": "channel-99",
        "fromTerra": "channel-5"
      },
      "explorer": {
        "address": "https://ping.pub/decentr/account/{}",
        "tx": "https://ping.pub/decentr/tx/{}",
        "validator": "https://ping.pub/decentr/validators/{}",
        "block": "https://ping.pub/decentr/blocks/id/{}"
      }
    },
    "juno-1": {
      "chainID": "juno-1",
      "lcd": "https://lcd-juno.mib.tech",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ujuno": 0.0025
      },
      "prefix": "juno",
      "coinType": "118",
      "baseAsset": "ujuno",
      "name": "Juno",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Juno.svg",
      "ibc": {
        "fromTerra": "channel-2",
        "toTerra": "channel-86",
        "ics": {
          "contract": "juno1v4887y83d6g28puzvt8cl0f3cdhd3y6y9mpysnsp3k8krdm7l6jqgm0rkn",
          "toTerra": "channel-154",
          "fromTerra": "channel-33"
        },
        "icsFromTerra": {
          "contract": "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
          "toTerra": "channel-153",
          "fromTerra": "channel-32"
        }
      },
      "explorer": {
        "address": "https://www.mintscan.io/juno/account/{}",
        "tx": "https://www.mintscan.io/juno/txs/{}",
        "validator": "https://www.mintscan.io/juno/validators/{}",
        "block": "https://www.mintscan.io/juno/blocks/id/{}"
      }
    },
    "kaiyo-1": {
      "chainID": "kaiyo-1",
      "lcd": "https://kujira-api.polkachu.com",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ukuji": 0.00119,
        "ibc/DA59C009A0B3B95E0549E6BF7B075C8239285989FF457A8EDDBB56F10B2A6986": 0.000625,
        "ibc/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F": 0.0015
      },
      "prefix": "kujira",
      "coinType": "118",
      "baseAsset": "ukuji",
      "name": "Kujira",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Kujira.png",
      "ibc": {
        "fromTerra": "channel-10",
        "toTerra": "channel-5",
        "icsFromTerra": {
          "contract": "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
          "toTerra": "channel-36",
          "fromTerra": "channel-28"
        }
      },
      "alliance": true,
      "explorer": {
        "address": "https://www.mintscan.io/kujira/account/{}",
        "tx": "https://www.mintscan.io/kujira/txs/{}",
        "validator": "https://www.mintscan.io/kujira/validators/{}",
        "block": "https://www.mintscan.io/kujira/blocks/id/{}"
      }
    },
    "mars-1": {
      "chainID": "mars-1",
      "lcd": "https://rest.marsprotocol.io",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "umars": 0
      },
      "prefix": "mars",
      "coinType": "330",
      "baseAsset": "umars",
      "name": "Mars",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Mars.svg",
      "version": "0.46",
      "ibc": {
        "fromTerra": "channel-78",
        "toTerra": "channel-2"
      },
      "explorer": {
        "address": "https://explorer.marsprotocol.io/accounts/{}",
        "tx": "https://explorer.marsprotocol.io/transactions/{}",
        "validator": "https://explorer.marsprotocol.io/validators/{}",
        "block": "https://explorer.marsprotocol.io/blocks/{}"
      }
    },
    "migaloo-1": {
      "chainID": "migaloo-1",
      "lcd": "https://ww-migaloo-rest.polkachu.com",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uwhale": 0.25
      },
      "prefix": "migaloo",
      "coinType": "118",
      "baseAsset": "uwhale",
      "name": "Migaloo",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Migaloo.svg",
      "alliance": true,
      "ibc": {
        "fromTerra": "channel-86",
        "toTerra": "channel-0",
        "icsFromTerra": {
          "contract": "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
          "toTerra": "channel-2",
          "fromTerra": "channel-87"
        }
      },
      "explorer": {
        "address": "https://ping.pub/migaloo/account/{}",
        "tx": "https://ping.pub/migaloo/tx/{}",
        "validator": "https://ping.pub/migaloo/validators/{}",
        "block": "https://ping.pub/migaloo/blocks/id/{}"
      }
    },
    "osmosis-1": {
      "chainID": "osmosis-1",
      "lcd": "https://osmosis-1.terra.dev",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uosmo": 0.025
      },
      "prefix": "osmo",
      "coinType": "118",
      "baseAsset": "uosmo",
      "name": "Osmosis",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Osmosis.svg",
      "ibc": {
        "toTerra": "channel-251",
        "fromTerra": "channel-1",
        "icsFromTerra": {
          "contract": "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
          "toTerra": "channel-341",
          "fromTerra": "channel-26"
        }
      },
      "explorer": {
        "address": "https://www.mintscan.io/osmosis/account/{}",
        "tx": "https://www.mintscan.io/osmosis/txs/{}",
        "validator": "https://www.mintscan.io/osmosis/validators/{}",
        "block": "https://www.mintscan.io/osmosis/blocks/id/{}"
      }
    },
    "stride-1": {
      "chainID": "stride-1",
      "lcd": "https://stride-fleet.main.stridenet.co/api",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "ustrd": 0
      },
      "prefix": "stride",
      "coinType": "118",
      "baseAsset": "ustrd",
      "name": "Stride",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Stride.png",
      "ibc": {
        "fromTerra": "channel-46",
        "toTerra": "channel-52"
      },
      "explorer": {
        "address": "https://www.mintscan.io/stride/account/{}",
        "tx": "https://www.mintscan.io/stride/txs/{}",
        "validator": "https://www.mintscan.io/stride/validators/{}",
        "block": "https://www.mintscan.io/stride/blocks/id/{}"
      }
    },
    "phoenix-1": {
      "chainID": "phoenix-1",
      "lcd": "https://phoenix-lcd.terra.dev",
      "gasAdjustment": 1.75,
      "gasPrices": {
        "uluna": 0.015
      },
      "prefix": "terra",
      "coinType": "330",
      "baseAsset": "uluna",
      "name": "Terra",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Terra.svg",
      "alliance": true,
      "explorer": {
        "address": "https://terrasco.pe/mainnet/address/{}",
        "tx": "https://terrasco.pe/mainnet/tx/{}",
        "validator": "https://terrasco.pe/mainnet/validator/{}",
        "block": "https://terrasco.pe/mainnet/block/{}"
      }
    }
  },
  "testnet": {
    "uni-6": {
      "chainID": "uni-6",
      "lcd": "https://juno-testnet-api.polkachu.com",
      "gasAdjustment": 2,
      "gasPrices": {
        "ujunox": 0.015
      },
      "prefix": "juno",
      "coinType": "118",
      "baseAsset": "ujunox",
      "name": "Juno",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Juno.svg",
      "explorer": {
        "address": "https://testnet.juno.explorers.guru/account/{}",
        "tx": "https://testnet.juno.explorers.guru/transaction/{}",
        "validator": "https://testnet.juno.explorers.guru/validator/{}",
        "block": "https://testnet.juno.explorers.guru/block/{}"
      }
    },
    "ares-1": {
      "chainID": "ares-1",
      "lcd": "https://testnet-rest.marsprotocol.io",
      "gasAdjustment": 2,
      "gasPrices": {
        "umars": 0
      },
      "prefix": "mars",
      "coinType": "330",
      "baseAsset": "umars",
      "name": "Mars",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Mars.svg",
      "ibc": {
        "toTerra": "channel-0",
        "fromTerra": "channel-189"
      },
      "version": "0.46",
      "explorer": {
        "address": "https://testnet-explorer.marsprotocol.io/accounts/{}",
        "tx": "https://testnet-explorer.marsprotocol.io/transactions/{}",
        "validator": "https://testnet-explorer.marsprotocol.io/validators/{}",
        "block": "https://testnet-explorer.marsprotocol.io/blocks/{}"
      }
    },
    "atlantic-2": {
      "chainID": "atlantic-2",
      "lcd": "https://sei-testnet-api.polkachu.com",
      "gasAdjustment": 2,
      "gasPrices": {
        "usei": 0.01
      },
      "prefix": "sei",
      "coinType": "118",
      "baseAsset": "usei",
      "name": "Sei",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Sei.png",
      "ibc": {
        "fromTerra": "channel-100",
        "toTerra": "channel-11"
      },
      "explorer": {
        "address": "https://sei.explorers.guru/account/{}",
        "tx": "https://sei.explorers.guru/transaction/{}",
        "validator": "https://sei.explorers.guru/validator/{}",
        "block": "https://sei.explorers.guru/block/{}"
      }
    },
    "pisco-1": {
      "chainID": "pisco-1",
      "lcd": "https://pisco-lcd.terra.dev",
      "gasAdjustment": 3.5,
      "gasPrices": {
        "uluna": 0.015
      },
      "prefix": "terra",
      "coinType": "330",
      "baseAsset": "uluna",
      "name": "Terra",
      "icon": "https://200fdcb6.station-assets.pages.dev/img/chains/Terra.svg",
      "alliance": true,
      "explorer": {
        "address": "https://terrasco.pe/testnet/address/{}",
        "tx": "https://terrasco.pe/testnet/tx/{}",
        "validator": "https://terrasco.pe/testnet/validator/{}",
        "block": "https://terrasco.pe/testnet/block/{}"
      }
    }
  }
}

thias is the full config on testing

**Comment by StrathCole** [comment]
You can also use an own script that uses terrad with the correct chainid and node arguments. I only use terrain to optimize/compile the contracts and deploy via terrad.

**Comment by garudanodes** [comment]
thank you for the reply brother @inon-man and @StrathCole we found way to deploy it i will close this issues
