### ISSUE TITLE
[BUG] Investigate ICA Host Msgs AnteHandler Circumvention

### ISSUE THREAD

**Issue by fragwuerdig** [classic-terra/core#298]
**Describe the bug**

Protocol Messages carried out via ICA might circumvent the Ante Handler. Which in turn circumvents any custom chain logic including tax handling. This needs to be proven.

- [ ] Setup testnet with ibc-go v6.0 and ICA controller enabled.
- [x] Enable ICA Host messages via gov on rebel-2
- [ ] Setup IBC relayer
- [ ] Conduct to show whether tax is avoided or not when control host via ICA.

**Comment by nghuyenthevinh2000** [comment]
should I close this one?
