### ISSUE TITLE
[BUG] Smart Contract Issued Address Longer Than the terra1 + 38 alphanumeric character validation After Chain Upgrade

### ISSUE THREAD

**Issue by aeuser999** [classic-terra/core#317]
**Describe the bug**
It seems, upon one persons report, that smart contract addresses that are issued after the last core upgrade may be longer than the standard for validation rules in certain endpoints (validation rule of:  terra1 + 38 characters of a-z or 0-9 for accounts).

**To Reproduce**
For FCD:
```
https://terra-classic-fcd.publicnode.com/v1/txs?limit=100&account=terra1txgelkw2pyldrfhkzwhsrzr6eagxecfm8klgrcf44q8a5hagefdsclmuvz
```

**Context & versions**
Person mentioned they tried this call:
```
https://terra-classic-fcd.publicnode.com/v1/txs?limit=100&account=terra1txgelkw2pyldrfhkzwhsrzr6eagxecfm8klgrcf44q8a5hagefdsclmuvz
```
And it gave them back:
```
{"type":"INVALID_REQUEST_ERROR","message":"child "account" fails because ["account" with value "terra1txgelkw2pyldrfhkzwhsrzr6eagxecfm8klgrcf44q8a5hagefdsclmuvz" fails to match the required pattern: /^terra1[a-z0-9]{38}$/]","code":400}
```

Yet, it does find the account on finder:
- [https://finder.terra.money/mainnet/address/terra1txgelkw2pyldrfhkzwhsrzr6eagxecfm8klgrcf44q8a5hagefdsclmuvz](https://finder.terra.money/mainnet/address/terra1txgelkw2pyldrfhkzwhsrzr6eagxecfm8klgrcf44q8a5hagefdsclmuvz)

The person mentioned:  "The contract address after the chain upgrade is so long, it seems that fcd is not compatible with this rule
Hope to fix it soon"

Here is the link to the original post:
- [https://discord.com/channels/984128262311645254/1039705031710089247/1136545326187171900](https://discord.com/channels/984128262311645254/1039705031710089247/1136545326187171900)

**Comment by nghuyenthevinh2000** [comment]
yes, the smart contract address length has been raised to 32 bytes: https://github.com/classic-terra/wasmd/blob/v0.30.x-terra/x/wasm/types/types.go#L17

This is to allow longer IBC contract address length. I don't t think front - end has reflected this correctly. I will inform @echel0n-HX about this.

**Comment by echel0n-TR** [comment]
@aeuser999 this issue is now fixed on our FCD, please confirm on your end as well
```
https://fcd.terraclassic.community/v1/txs?limit=100&account=terra1txgelkw2pyldrfhkzwhsrzr6eagxecfm8klgrcf44q8a5hagefdsclmuvz
```

**Comment by aeuser999** [comment]
Hi @echel0n-TR ,

Yes, it seems to work on:

```
https://fcd.terraclassic.community/v1/txs?limit=100&account=terra1txgelkw2pyldrfhkzwhsrzr6eagxecfm8klgrcf44q8a5hagefdsclmuvz
```

I guess my question is why did it throw that message?  Is it just that PublicNodes is using an old version of FCD?  I could not see where it actually would test the account length (or call to have it tested elsewhere):
- [https://github.com/classic-terra/fcd-classic/blob/036417f8954a95b82952ef8ecd25445923282933/src/service/transaction/getTxList.ts#L129](https://github.com/classic-terra/fcd-classic/blob/036417f8954a95b82952ef8ecd25445923282933/src/service/transaction/getTxList.ts#L129)

I did note that the tests for FCD all list valid addresses for the test as terra1 + 38 character length addresses rather than 58 character length addresses (ie. /^terra1[a-z0-9]{38,58}$/]:
- Example:  [https://github.com/classic-terra/fcd-classic/blob/classic-main/src/e2etest/tx.spec.ts#L6](https://github.com/classic-terra/fcd-classic/blob/classic-main/src/e2etest/tx.spec.ts#L6)

But, yes, I confirm it is working on the FCD you mentioned.

**Comment by aeuser999** [comment]
Ahh... ha..  It was in src/lib/constant.ts .  I guess that is what I get for trying to figure it out quickly and use github repo search instead of a dev environment (and now it seems to find it, it didn't when I tried earlier).  Thank You :)

I believe AllNodes is running the infrastructure for PublicNodes (and TFL has their fcd.terra.dev endpoint pointed there if I remember correctly).

I see also that it is fixed in the classic-terra/fcd-classic repo as well:
- [https://github.com/classic-terra/fcd-classic/blob/036417f8954a95b82952ef8ecd25445923282933/src/lib/constant.ts#L4](https://github.com/classic-terra/fcd-classic/blob/036417f8954a95b82952ef8ecd25445923282933/src/lib/constant.ts#L4)

So, looks like it is just PublicNodes is not using an updated FCD.

Thank You :)
