### ISSUE TITLE
[BUG] v2.2.0 does not support height query as before

### ISSUE THREAD

**Issue by inon-man** [classic-terra/core#332]
## Description
It's always returning the latest state regardless of height query parameter
e.g. http://localhost:1317/terra/oracle/v1beta1/denoms/exchange_rates?height=500000

This is a side effect of the removal of REST support from CosmosSDK v0.46.x.

**Comment by nghuyenthevinh2000** [comment]
uh, I don't get this one

It always returns latest height is normal behaviour and there is also no height params to the query above as well

<img width="1428" alt="Screenshot 2023-08-29 at 08 14 10" src="https://github.com/classic-terra/core/assets/23058164/d679aaa7-aa6e-4357-9e7d-cddad5bc52fa">
