### ISSUE TITLE
[BUG] misleading error messages with new tax handling

### ISSUE THREAD

**Issue by StrathCole** [classic-terra/core#335]
It seems that the new tax handling throws different errors to what it has been before.
This leads to misleading messages with missing funds.

Prior to the upgrade if you forgot to send stability tax or sent too few fees, the result was like this:
```
code: 13
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'insufficient fees; got: "25000000uluna", required: "73798806uluna,1159722uusd"
  = "43798806uluna,1159722uusd"(gas) + "30000000uluna"(stability): insufficient fee'
timestamp: ""
tx: null
txhash: FBF20156B09AE0F346025E1203C3380E57E8CB23564104F7A4FEAF57048B7A74
```

But after the upgrade there seems to be a prior step that exits with an error for the same command:

```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = 25000000uluna is smaller than 27000000uluna: insufficient funds: insufficient funds [classic-terra/core/v2/custom/auth/ante/fee_burntax.go:33] With gas wanted: '18446744073709551615' and gas used: '46696' : unknown request
```

This could probably lead to some issues in error handling. Also the amount complained about seems strange.
The test amount sent was `15000000000uluna`, so tax should be 30000000 as the first error message correctly displays.

If you send `--fees 27000000uluna` along with the command, the "old" error message appears with the complaint about missing fees and the correct amount of stability tax.

**Comment by Spawn-666** [comment]
The Errorcode leads to classic-terra/core/v2/... ->> shouldn´t it be classic-terra/core/custom/auth/ante/fee_burntax.go   ?
