### ISSUE TITLE
[BUG] genesis.json: invalid character '\x00' in string literal

### ISSUE THREAD

**Issue by park1847** [classic-terra/core#358]
received the latest files from https://quicksync.io/networks/terra.html.
Synchronization was completed by running terrad 2.2.1
I turned the process on and off a few times, and the following error occurred.

Error: error reading GenesisDoc at /home/dev01/.terra/config/genesis.json: invalid character '\x00' in string literal
(execute fileversion : v2.2.1, v2.2.2, v2.2.2-rc.2 )

It was in operation since last year, but due to the 2.2.0 app hash error, only the data and executable files were updated and executed again.

**Comment by park1847** [comment]
After restarting the computer, the following message appears when running.

Error: failed to initialize database: resource temporarily unavailable

**Comment by nghuyenthevinh2000** [comment]
well, there are a lot of commands going on here.

what are commands that you used?

**Comment by park1847** [comment]
It works well now.
It's not reproducing again

> well, there are a lot of commands going on here.
> 
> what are commands that you used?
