### ISSUE TITLE
[BUG] How this is different from terra-money/classic-core?

### ISSUE THREAD

**Issue by pronvis** [classic-terra/core#403]
Hello!
What is the difference between this repo & https://github.com/terra-money/classic-core/ ?
related issue: https://github.com/terra-money/classic-core/issues/820

**Comment by nghuyenthevinh2000** [comment]
this is the up - to - date and active repo for Terra Classic

**Comment by VirtualWizzard** [comment]
what's the upto date reop for wrapped luna erc-20 ea9 contract address ?

both chains run native denom as "ULUNA"
