### ISSUE TITLE
[FEATURE] Backport Min Initial Deposit

### ISSUE THREAD

**Issue by fragwuerdig** [classic-terra/core#41]
**Problem definition**
Currently the amount of spam proposals in Deposit phase is unbearable. In order to prevent spam in the Deposit phase it would be nice to have a min. initial Deposit that the proposer has to submit alongside the proposal. This feature is available in v0.47 of SDK. As we won't move to 47 in the near future it's probably legit to backport that feature.

- [x] Assess the viability of this task
- [x] Backport the feature
- [x] Upgrade handlers

**Comment by ZaradarBH** [comment]
Gov proposal is handled under this issue: https://github.com/classic-terra/classic/issues/29

**Comment by fragwuerdig** [comment]
Here is classys prop on the agora:

https://classic-agora.terra.money/t/initiative-to-increase-luna-classic-proposal-deposit-amount-from-0-to-200-000-lunc-v2/49700

Linked also the feature branch to this.

**Comment by LuncBurner** [comment]
@fragwuerdig This item looks like it has some progress against it.  Should it be moved to in-progress status?
