### ISSUE TITLE
Governance Proposal for Cosmwasm v0.16.6 => v1.2.0

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#57]
**Problem definition**
A Governance proposal is required outlining the findings and recommended approach for the Cosmwasm upgrade.

**Additional context**
- [ ] Create an agora post outlining findings and recommended approach.
- [x]  Create a governance proposal which references the findings from the research conducted and recommends a proposed approach moving forward.

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/documents/blob/main/proposals/cosmwasm-upgrade-v0.16.6-to-v1.2.0-05022023.md

**Comment by StrathCole** [comment]
> https://github.com/classic-terra/documents/blob/main/proposals/cosmwasm-upgrade-v0.16.6-to-v1.2.0-05022023.md

This implies option 4?

**Comment by LuncBurner** [comment]
@StrathCole I believe this does in fact state option #4.

**Comment by edk208** [comment]
the only thing that I might change is add some details to this,
Approve the mandatory migration of smart contracts from wasmvm v0.16.6 to wasmvm v1.2.0.

Around what does this mean for those contracts that do not upgrade.... otherwise LGTM

**Comment by ZaradarBH** [comment]
I added this comment: "Contracts that do not migrate will stop functioning as we do not have the funding (or desire) to support a "dual VM setup", unless absolutely necessary.". Will close this issue and consider it done. People can freely edit the source document in the documents repo :)

**Comment by LuncBurner** [comment]
Thanks @ZaradarBH I will post to Agora for discussion.
