### ISSUE TITLE
Test Columbus-5 Genesis Import And Sync

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#60]
**Problem definition**
Test import of columbus-5 genesis file and sync from genesis.

**Feature specification**
Columbus-5 genesis.json file loads correctly and syncs.

**Additional context**
- [x] Test import of file and confirm if there is an issue.
- [x] Sync a full node from genesis
- [x] Test using the latest v1.0.5-archive release

**Comment by ZaradarBH** [comment]
https://github.com/terra-rebels/classic/releases/tag/v1.0.4
https://genesis.terrarebels.net/mainnet/columbus-5/columbus-5-genesis.json
https://genesis.terrarebels.net/mainnet/columbus-5/addrbook.json

**Comment by edk208** [comment]
duplicate issues.. linking them here 
https://github.com/classic-terra/core/issues/59
https://github.com/classic-terra/core/issues/88

**Comment by ZaradarBH** [comment]
I think we just need @inon-man confirmation to close this :)

**Comment by inon-man** [comment]
Confirmed it is working with tag v1.0.5-full-archive.

**Comment by inon-man** [comment]
It is still in progress without error.

**Comment by inon-man** [comment]
Current synced height [5974079](https://finder.terra.money/classic/blocks/5974078)
