### ISSUE TITLE
IBC Relayer

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#65]
**Problem definition**
After @faddat leaving the L1 there might be a threat of notional taking down relayers to Osmosis. Might be viable to set up an own relayer.

- [ ] Assess funding for this (we kinda need VPS with 32GB RAM, 20TB SSD disk space, might be very expensive)
- [ ] Optionally use public archive nodes
- [ ] Create/install/configure Osmosis full archive node
- [ ] Assess whether it's possible to use Classic full archive node from TCV
- [ ] Create/install hermes relayer
- [ ] Configuration of hermes relayer

**Comment by fragwuerdig** [comment]
Hey @LuncBurner. We might need a dedicated (and probably expensive) VPS for this in order to setup a Osmosis full archive node. Optionally we can use a public node - but from my experience that is quite unstable (because of rate limiting in public nodes). I guess we need to discuss this further...

**Comment by LuncBurner** [comment]
@fragwuerdig Can we obtain a cost estimate for running this infrastructure?  Can this be run on AWS?

**Comment by fragwuerdig** [comment]
We need several thing to run this infra:

1) archive nodes for the involved chains (~$2000)
2) an VPS running the actual relay (~$100)
3) relay fee payment (~$1000 - $10.000 depending on volume)

**Comment by LuncBurner** [comment]
Is item #1 a monthly OPEX cost, or is it a one-time fee?

**Comment by nghuyenthevinh2000** [comment]
> 

that should be the amount

**Comment by fragwuerdig** [comment]
> Is item #1 a monthly OPEX cost, or is it a one-time fee?

This is monthly.

**Comment by VirtualWizzard** [comment]
WHERE IS MY TECH PAYMENTS @nghuyenthevinh2000 @fragwuerdig @ZaradarBH @LuncBurner @zmanian
