### ISSUE TITLE
Enable IBC for wasm

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [classic-terra/core#66]
**Problem definition**
Currently, IBC feature is not available on x/wasm. This will prohibit smart contract from going cross - chain.

**Feature specification**
Enable IBC feature on x/wasm will allow dapp to go cross - chain. I am willing to host sessions, write documents to show how to write cross - chain smart contract.

Going cross - chain is the current trend of the whole Cosmos ecosystem:
* cross - chain swap
* cross - chain NFT marketplace
* cross - chain name service

We should embrace this trend

@ZaradarBH @inon-man @fragwuerdig 

**Additional context**
- [ ]

**Comment by fragwuerdig** [comment]
Does this feature need Interchain Accounts ICS-27? Because until version 3.0 of IBC-GO there is pretty much only the transfer (ICS-20) app available... @nghuyenthevinh2000

**Comment by nghuyenthevinh2000** [comment]
Yes, let's talk. I can outline plan for this goal

**Comment by arunadaybasu** [comment]
Try and check if Hermes works:
https://github.com/informalsystems/hermes

**Comment by nghuyenthevinh2000** [comment]
IBC is included in next wasmd upgrade v0.30.0
