### ISSUE TITLE
Separate burn wallet that is exempt from seigniorage (could skip if we don’t want to do)

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#70]

**Comment by StrathCole** [comment]
Is that necessary when the ante handler is modified?

**Comment by ZaradarBH** [comment]
Assigned this to Luncburner until its refined

**Comment by fragwuerdig** [comment]
is this related to #100??

**Comment by StrathCole** [comment]
> is this related to #100??

Should be, yes.

**Comment by ZaradarBH** [comment]
Closed in favor of #100
