### ISSUE TITLE
Classic v1.0.6 Governance Proposal

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#80]
**Problem definition**
A governance proposal for Classic v1.0.6 is required for the proposed whitelist changes to be accepted and pushed into production.

**Feature specification**
Proposal writeup and listing of Binance wallet addresses to be whitelisted.

**Additional context**
- [x] Write agora post for Classic v1.0.6
- [ ] publish proposal for Classic v1.0.6

**Comment by ZaradarBH** [comment]
@LuncBurner @edk208 We also need to include the antehandler split logic in this I assume? :)

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/documents/blob/main/proposals/1.0.6-release-candidate-01022023.md
