### ISSUE TITLE
Update IBC Go

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#86]
**Problem definition**
The current IBC version is outdated. We need to update the IBC-GO module to version 1.3.1

**Feature specification**
- [x] Undertake research on Juno
- [x] Implement the needed changes
- [x] Testing on local net

**Additional context**
.

**Acceptance Criteria**
- [x] Successfully upgrade to 1.3.1 and confirm correct functionality

**Comment by fragwuerdig** [comment]
I noticed that ibc-go 3.4.0 is already part of main. But I think it's not tested.

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/core/pull/93

**Comment by ZaradarBH** [comment]
@fragwuerdig I updated the dependencies in the PR above. If you can find time to test it vs rebel-2 that would be epic. Also I am not sure what research we are doing on Juno?

**Comment by fragwuerdig** [comment]
Can we test this on rebel-2 as soon as we have a release candidate for 1.0.6? I would prefer to check that particular branch against a local net. We should really only test RCs against rebel-2, imho.

**Comment by inon-man** [comment]
> Can we test this on rebel-2 as soon as we have a release candidate for 1.0.6? I would prefer to check that particular branch against a local net. We should really only test RCs against rebel-2, imho.
> 
> You can remove that Juno research thing. I Just wanted to learn how to upgrade that particular dependency.

Could you please tell me what rebel-2 is? Sorry.

**Comment by fragwuerdig** [comment]
@inon-man: That's the testnet. Please have a look into the slack server channel #testnet.
