### ISSUE TITLE
[BUG] Function Call Result Struct gets Accessed Without Error Check

### ISSUE THREAD

**Issue by fragwuerdig** [classic-terra/core#94]
Tried to do a bank send from a local terrad client and spotted the following error:

![image](https://user-images.githubusercontent.com/29800180/217227661-aabaf886-72d9-4172-b260-1f9400c613c3.png)

The error is a result of the following code snipped, where the resulting struct of a call was accessed without checking the error status of the call:

![image](https://user-images.githubusercontent.com/29800180/217228047-cdc6db8a-6a72-4aab-94b0-4b9366c7c7a0.png)

It's worth scanning the code base for such errors.

**Comment by edk208** [comment]
just rehashing here what was said in the slack.  this looks more like a network issue using the --node parameter.  The RPC needs to be open to the public, and accept connections.  What possibly looked like a CORS issue with the post could have just been a gas mismatch where the tx didnt' have enough gas and was floating around in the mempool.

**Comment by nghuyenthevinh2000** [comment]
there are several lines like so

**Comment by ZaradarBH** [comment]
@inon-man, @nghuyenthevinh2000 and I discussed adding a nil check to the CLI client code, so once @inon-man merges the fix into our new main we should at least not get a panic anymore, which is good because unhandled exceptions should never occur and if when they do you need to fix/handle them :)
