### ISSUE TITLE
Create documentation outlining Smart Contract wasmvm upgrade steps

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#99]
**Problem definition**
Create documentation outlining wasmvm smart contract migration

**Feature specification**
- [ ] Review input from @StrathCole about potential deviations we need to take into account
- [ ] Present initial draft for internal review
- [ ] Finalize and publish updated documentation

**Additional context**
.

**Acceptance criteria**
- [ ] Documentation is published
- [ ] Approved by @StrathCole

**Comment by ZaradarBH** [comment]
I think we can just copy this to be honest @ https://docs.terra.money/develop/guides/smart-contracts/upgrade-cosmwasm

**Comment by StrathCole** [comment]
> I think we can just copy this to be honest @ https://docs.terra.money/develop/guides/smart-contracts/upgrade-cosmwasm

That will not be enough I think (if I remember correctly) as classic uses the querier e.g. for tax rates, depending on the base contract that might be "terraswap" library which is not supported on 1.2.x afaik.
But I need to re-check what I had to do to make my contracts compatible.

**Comment by ZaradarBH** [comment]
@StrathCole guess who just earned himself a VIP ticket to the "review party" :P

**Comment by StrathCole** [comment]
The code for tax calculation in Smart Contract on classic for example looks like this:
```
fn compute_tax(querier: &QuerierWrapper, amount: Uint128, denom: String) -> StdResult<Uint128> {
    let terra_querier = TerraQuerier::new(querier);
    let tax_rate: Decimal = (terra_querier.query_tax_rate()?).rate;
    let tax_cap: Uint128 = (terra_querier.query_tax_cap(denom)?).cap;
    Ok(std::cmp::min(
        amount.checked_sub(amount.multiply_ratio(
            DECIMAL_FRACTION,
            (DECIMAL_FRACTION * tax_rate) + DECIMAL_FRACTION,
        ))?,
        tax_cap,
    ))
}
```
The issue is that TerraQuerier is not necessary on mainnet as there is no tax to query. So I think that feature was removed. We need to check how the tax can be queried by smart contracts after code parity.

**Comment by StrathCole** [comment]
This could be an issue.
![Bildschirmfoto von 2023-02-14 10-11-07](https://user-images.githubusercontent.com/7449529/218690613-e887d0f8-9841-4a4c-9d6d-2a0c7b5e844f.png)

Didn't have in mind that this package is deprecated and incompatible with mainnet, but will be needed on classic later. So we need to check for how to query the oracle and tax information from the contracts. Either the terra-cosmwasm needs adjustment to work with upgraded classic or we need to look for an alternative.

**Comment by ZaradarBH** [comment]
@shackra might be able to help with some of the update work if we just provide him with the edits in a portable format (e.g. mark-down or rich text)

**Comment by StrathCole** [comment]
The problem we have @ZaradarBH is, that we have no way to test this at the moment. Mainnet has no tax and classic/classic test has no wasm 1.x
That means I can say what I need to do to update for mainnet, but what will happen with classic after upgrade due to the tax I have no clue, yet.

**Comment by ZaradarBH** [comment]
> The problem we have @ZaradarBH is, that we have no way to test this at the moment. Mainnet has no tax and classic/classic test has no wasm 1.x That means I can say what I need to do to update for mainnet, but what will happen with classic after upgrade due to the tax I have no clue, yet.

I think we should be able to setup a dedicate testnet with the configuration we need to test the upgrade process once we are past the v1.1.0 release at the end of the month.  Right now we are all very focused on that deadline, so until then lets try to figure out all the "test cases" we want to perform and then we can break those off into other issues once we commence the work? :)
